# Karpet server config
# For karpet 0.0.2 ALPHA

[server]
port = 25565 # Server port
icon = "server.png" # Server icon, does not work at the moment due to a bug idk how to fix
desc = "My amazing server" # Description of server
show-player-names = false # Show player names on server list
online-mode = true # Authenticate players
max-players = 0


[afk]
afk-kick = false # Enable AFK kick
afk-kick-time = 20 # Time in mins until the afk kick kicks the player

[world]
world-name = "epic_world" # Folder name of the world
worlds-folder = "worlds" # Location of all world files
gamemode = "survival" # Server gamemode, survival/creative/adventure

[whitelist]
enable-whitelist = true # Enable whitelist or not
banned-players = ["urmom"] # Banned player names, people can get around this if the server runs in offline mode
banned-ips = ["93.343.324.1"] # Banned IP addresses

[chat]
enable-chat = true # Enable Chat
announce-player-join = true # Player join message
announce-player-leave = true # Player leave message


